version: &imageVersion "14258062653"
global:
  version: *imageVersion
okto-sdk-docs-v2:
  environment: production
  project: okto
  namespaceOverride: oktohq
  image:
    registry: ghcr.io
    repository: okto-hq/okto-sdk-docs-v2
    pullPolicy: IfNotPresent
    tag: *imageVersion
  imagePullSecrets:
    - name: oktohq-registry
  deployment:
    resources:
      limits:
        cpu: 700m
        memory: 700Mi
      requests:
        cpu: 500m
        memory: 500Mi
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 2
    DDService: okto-sdk-docs-v2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: ScheduleAnyway
  service:
    # serviceName: 
    ports:
      - port: 3000
        portName: http
        protocol: TCP
    type: ClusterIP
  ingress:
    enabled: true
    domain: okto.tech
    exposePort: http
    scheme: http
    hosts:
      - host: docsv2.okto.tech
      - host: docs.okto.tech
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  envFromSecrets:
    - variable: val1
      secretId: &oktohq-sdk-docs oktohq/okto-sdk-docs
      secretKey: val1
    - variable: NEXT_PUBLIC_GOOGLE_CLIENT_ID
      secretId: *oktohq-sdk-docs
      secretKey: NEXT_PUBLIC_GOOGLE_CLIENT_ID
  externalSecret:
    skipSecrets:
      - oktohq/okto-sdk-docs
  tolerations:
    - effect: NoSchedule
      key: application
      operator: Equal
      value: okto
    - effect: NoSchedule
      key: arch
      operator: Equal
      value: arm64
  nodeSelector:
    application: okto
    arch: arm64
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsGroup: 7777
    runAsUser: 7777
  deploymentStrategy:
    rollingUpdate:
      maxUnavailable: 50%
